const assert=require('node:assert/strict');
const {chromium}=require(process.env.GRAPH_PLAYWRIGHT_MODULE);
const base=process.env.GRAPH_BROWSER_BASE;
(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:process.env.GRAPH_BROWSER_EXECUTABLE,args:['--no-sandbox']});
  const page=await browser.newPage({viewport:{width:1600,height:1100}}),errors=[],requests=[];
  page.setDefaultTimeout(15000);page.on('dialog',dialog=>dialog.accept());
  page.on('pageerror',e=>errors.push(e.message));
  page.on('request',r=>{if(new URL(r.url()).pathname.startsWith('/api/'))requests.push([r.method(),new URL(r.url()).pathname]);});
  await page.goto(base+'/dependencies');await page.waitForFunction(()=>document.querySelectorAll('.graph-node').length===5);
  assert.equal(await page.locator('.graph-edge').count(),4);
  assert.equal(await page.locator('#graph-analyze,#graph-auto,[data-action]').count(),0);
  const pairs=()=>page.locator('.graph-edge').evaluateAll(es=>es.map(e=>e.dataset.edge).sort());
  assert.deepEqual(await pairs(),['a0000001:b0000002','a0000001:c0000003','b0000002:d0000004','c0000003:d0000004']);
  const positions=()=>page.locator('.graph-node').evaluateAll(ns=>Object.fromEntries(ns.map(n=>[n.dataset.node,n.getAttribute('transform')])));
  const coords=s=>s.match(/-?\d+(?:\.\d+)?/g).map(Number);
  let p=await positions();assert(coords(p.a0000001)[0]<coords(p.b0000002)[0]);assert.equal(coords(p.b0000002)[0],coords(p.c0000003)[0]);assert(coords(p.b0000002)[0]<coords(p.d0000004)[0]);assert.notEqual(coords(p.b0000002)[1],coords(p.c0000003)[1]);
  assert.equal(await page.locator('[data-edge*="e0000005"]').count(),0);
  await page.screenshot({path:process.env.GRAPH_SCREENSHOT_DIR+'/fork-join.png',fullPage:true});
  await page.locator('[data-node="d0000004"]').click();
  assert((await page.locator('#graph-detail').textContent()).includes('とても長いタイトル'));
  await page.getByRole('link',{name:'既存スケジュールを開く →'}).click();
  await page.waitForURL('**/tasks/d0000004#schedule-box');
  await page.locator('#schedule-box').waitFor({state:'visible'});
  // Use the EXISTING schedule screen to cancel and replace the dependencies.
  const fixture=await (await page.request.get(base+'/fixture/calls')).json();
  await page.locator(`.sched-cancel[data-sid="${fixture.schedule_id}"]`).click();
  await page.locator('#instruction').fill('新しい手動予約');
  await page.locator('#delivery-after').check();
  await page.locator('.sched-dep[value="b0000002"]').check();
  await page.locator('#schedule-btn').click();
  await page.waitForFunction(()=>document.querySelector('#scheduled-items').textContent.includes('新しい手動予約'));
  await page.goto(base+'/dependencies');await page.waitForFunction(()=>document.querySelectorAll('.graph-edge').length===3);
  assert.deepEqual(await pairs(),['a0000001:b0000002','a0000001:c0000003','b0000002:d0000004']);
  await page.locator('[data-edge="b0000002:d0000004"]').click();
  assert((await page.locator('#graph-detail').textContent()).includes('新しい手動予約'));
  const href=await page.getByRole('link',{name:'該当スケジュールを開く →'}).getAttribute('href');assert(href.includes('#scheduled-'));
  await page.getByRole('link',{name:'該当スケジュールを開く →'}).click();
  await page.waitForURL('**/tasks/d0000004#scheduled-*');
  await page.locator('#'+href.split('#')[1]).waitFor({state:'visible'});
  await page.getByRole('link',{name:'依存グラフ',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.graph-edge').length===3);
  await page.locator('[data-node="b0000002"]').click();const stable=await positions(),transform=await page.locator('#graph-world').getAttribute('transform');
  await page.request.post(base+'/fixture/status');await page.waitForFunction(()=>document.querySelector('[data-node="a0000001"]').textContent.includes('実行中'));
  assert.deepEqual(await positions(),stable);assert.equal(await page.locator('#graph-world').getAttribute('transform'),transform);
  assert((await page.locator('#graph-detail').textContent()).includes('B 並列作業'));
  await page.locator('#graph-project').selectOption('/fixture/repo-two');assert.equal(await page.locator('.graph-node.contextual').count(),2);
  assert((await page.locator('.graph-node.contextual').first().textContent()).includes('絞込み外の前提'));
  await page.locator('#graph-project').selectOption('');
  await page.getByRole('button',{name:'縦配置',exact:true}).click();assert(coords((await positions()).a0000001)[1]<coords((await positions()).b0000002)[1]);
  await page.getByRole('button',{name:'横配置',exact:true}).click();
  await page.getByRole('button',{name:'拡大',exact:true}).click();await page.getByRole('button',{name:'縮小',exact:true}).click();
  const beforePan=await page.locator('#graph-world').getAttribute('transform'),viewport=await page.locator('#graph-viewport').boundingBox();
  await page.mouse.move(viewport.x+10,viewport.y+10);await page.mouse.down();await page.mouse.move(viewport.x+70,viewport.y+50);await page.mouse.up();assert.notEqual(await page.locator('#graph-world').getAttribute('transform'),beforePan);
  await page.request.post(base+'/fixture/stress');await page.waitForFunction(()=>document.querySelectorAll('.graph-node').length===100);
  await page.getByRole('button',{name:'全体表示',exact:true}).click();
  assert(await page.evaluate(()=>{const a=document.querySelector('#graph-world').getBoundingClientRect(),b=document.querySelector('#graph-viewport').getBoundingClientRect();return a.top>=b.top&&a.bottom<=b.bottom&&a.left>=b.left&&a.right<=b.right;}));
  await page.locator('#graph-search').fill('f0000042');assert.equal(await page.locator('.graph-node').count(),1);
  await page.locator('.graph-node').click();assert((await page.locator('#graph-detail').textContent()).includes('独立タスク 42'));
  await page.locator('#graph-search').fill('');await page.getByRole('button',{name:'全体表示',exact:true}).click();
  await page.screenshot({path:process.env.GRAPH_SCREENSHOT_DIR+'/100-tasks.png',fullPage:true});
  await page.reload();await page.waitForFunction(()=>document.querySelectorAll('.graph-node').length===100);
  assert.equal((await (await page.request.get(base+'/fixture/calls')).json()).calls,0);
  assert(!requests.some(([method,path])=>path.startsWith('/api/dependency-graph')&&method!=='GET'));
  assert.deepEqual(errors,[]);await browser.close();console.log('PASS: manual fork/join, independent nodes, existing schedule editing, details, state/layout, filter, pan/zoom, 100 tasks, AI calls=0');
})().catch(e=>{console.error(e);process.exit(1);});
